rtl8721c: Resolved compilation error caused by _tolower()
../iot-core/src/easysetup/http/iot_easysetup_http_parser.c:33:
../realtek/amebad/swlib/string/strproc.h:67:21: error: expected identifier or '(' before 'unsigned'
 static inline char _tolower(const char c)
                     ^~~~~~~~
../realtek/amebad/swlib/string/strproc.h:67:35: error: expected ')' before '(' token
 static inline char _tolower(const char c)

Signed-off-by: baojun.luo <43360374+baojunluo@users.noreply.github.com>